#!/bin/sh
# (c) 2026, Roberto A. Foglietta <roberto.foglietta@gmail.com>, MIT license

export TERM=xterm PATH=/bin:/sbin:/usr/bin:/usr/sbin ENV=/etc/profile

# busybox install

if [ -x /bin/busybox ]; then
  /bin/busybox --install
  chmod +x /etc/init.d/rcS
  touch /etc/fstab
fi

# system uprising

mount -t proc procfs /proc
mount -t sysfs sysfs /sys
mount -o size=16k,nosuid -t devtmpfs tmpfs /dev
mkdir -p dev/pts && mount -t devpts devpts dev/pts;

echo 3 > /proc/sys/kernel/printk
echo Y > /sys/module/printk/parameters/time
grep -E "MemAvailable:|MemTotal:" /proc/meminfo

# caching filesystems

( find / >/dev/null 2>&1 & sleep 0.01 )

# temporary folder

tmpdir="/dev/shm"
mkdir -p $tmpdir/ && chmod +t $tmpdir
if grep -qw tmpfs /proc/filesystems; then
  ramsize=$(sed -ne "s/MemAvailable: *\([0-9]\+\) kB/\\1/p" /proc/meminfo)
  shmsize="65536"; [ $ramsize -le 131072 ] && shmsize=$(( ramsize >> 2 ))
  tmpdev=/dev/zram0;
  sb=/sys/block/zram0
  if [ -e $sb/reset ]; then
    echo 1 > $sb/reset
    echo ${shmsize}k > $sb/disksize
    zsize=$(( $(cat $sb/disksize) >> 10 ))
    shmsize=
  else
    tmpdev=tmpfs
  fi
  mount -o nosuid,nodev,${shmsize:+size=${shmsize}k} -t tmpfs $tmpdev $tmpdir
  if grep -q " $tmpdir " /proc/mounts; then
    echo "Temporary $tmpdir size is ${shmsize:-$zsize} kB of ${zsize:+Z}RAM"
  fi
fi
mkdir -p $tmpdir/ && chmod +t $tmpdir

# enviroment config
exec 3>/dev/nul

bttm=$(dmesg | sed -ne "s,\[ *\([0-9.]*\)*\] Run /init .*,\\1,p" | head -c4)
home=$(ls -1d /home /root / 2>/dev/null | tail -n1)

export HOME=$home TMPDIR=$tmpdir GZTMPDIR=/tmp GZUNGZIP=/bin/zcat
echo; uname -a | sed -e "s,\(x86_64\) x86_64 x86_64,\\1,"

entrp=$(cat /proc/sys/kernel/random/entropy_avail)
acnsl=$(sed '$s@.*[ /]@@' /sys/class/tty/console/active)
if uname -r | grep -qe "^5.15.201$" && which uchaos >&3; then
  echo | uchaos -qZk /dev/random | md5sum 2>&1 | grep . |\
    sed -e "s,  -$, --> /dev/random by uChaos,"
  entrq=$(cat /proc/sys/kernel/random/entropy_avail)
  printf "Active console: %s, entropy: %d -> %d bits\n" $acnsl $entrp $entrq
  source /etc/uctests
else
  printf "Active console: %s, entropy: %d bits\n" $acnsl $entrp
fi
echo -ne "\e[?7h
      ===============================================
      Welcome to Minimal Linux System for QEMU x86_64
       System dmsg time was ${bttm}s at the 1st console
      ===============================================
       type command 'reboot -f' to shutdown this VM
\n"
stty -echoctl
exec /linuxrc
