#!/bin/sh
# (c) 2026, Roberto A. Foglietta <roberto.foglietta@gmail.com>, MIT license

# system up rising

mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs none /dev

mkdir -p dev/pts &&
mount -t devpts dev/pts dev/pts;

echo Y > /sys/module/printk/parameters/time
echo 3 > /proc/sys/kernel/printk

if [ -r /bin/busybox ]; then
  mkdir -p /etc/init.d
  touch /etc/init.d/rcS /etc/fstab
  chmod +x /etc/init.d/rcS
fi

tmpdir="/dev/shm"
if ! grep -qw tmpfs /proc/filesystems; then
  ramsize=$(sed -ne "s/MemAvailable: *\([0-9]\+\) kB/\\1/p" /proc/meminfo)
  shmsize=$(( ( ramsize + 4096 ) >> 12 ))
  mount -o size=${shmsize}M,nodev,nosuid -t tmpfs none $tmpdir &&
  echo "Temporary $tmpdir uses max ${shmsize}M of system RAM"  || tmpdir="/tmp"
fi
mkdir -p $tmpdir/ && chmod +t $tmpdir

# caching filesystems

( find / >/dev/null 2>&1 & sleep 0.01 )

# enviroment config

#bttm=$(cut -d' ' -f1 /proc/uptime)
bttm=$(dmesg | sed -ne "s,\[ *\([0-9.]*\)*\] Run /init .*,\\1,p" | head -c4)
home=$(ls -1d /home /root / 2>/dev/null | tail -n1)
acnsl=$(sed '$s@.*[ /]@@' /sys/class/tty/console/active)
entrp=$(cat /proc/sys/kernel/random/entropy_avail)

export TERM=xterm HOME=$home PATH=/bin:/sbin:/usr/bin:/usr/sbin
export TMPDIR=$tmpdir GZTMPDIR=/tmp GZUNGZIP=/bin/zcat

echo
uname -a
stty -echoctl
echo -ne "Active console: $acnsl, entropy: $entrp bits
\e[?7h
      ===============================================
      Welcome to Minimal Linux System for QEMU x86_64
       System dmsg time was ${bttm}s at the 1st console
      ===============================================
       type command 'reboot -f' to shutdown this VM
"
exec /linuxrc
