#!/bin/sh
#
# (c) 2026, Roberto A. Foglietta <roberto.foglietta@gmail.com>, MIT license
#
export TERM=xterm PATH=/bin:/sbin:/usr/bin:/usr/sbin ENV=/etc/profile

# busybox install

if [ -x /bin/busybox ]; then
  /bin/busybox --install
  chmod +x /etc/init.d/rcS
  touch /etc/fstab
fi

# system uprising

mount -t proc procfs /proc
mount -t sysfs sysfs /sys
echo Y > /sys/module/printk/parameters/time
mount -o size=16k,nosuid -t devtmpfs tmpfs /dev
mkdir -p dev/pts && mount -t devpts devpts dev/pts

# 2nd stage switch

bttm=$(dmesg | sed -ne "s,\[ *\([0-9.]*\)*\] Run /init .*,\\1,p" | head -c8)
printf "\e[?7hRun /init exec /linuxrc\n"
export bttm
exec /linuxrc
stty -echoctl
echo
echo "Emergency shell respowning because /linuxrc failed"
echo
while true; do /bin/sh; sleep 1; done
