#!/bin/sh

for f in uchaos RNG_test; do
  test ! -x /bin/$f -a -x /bin/$f.gz.sh && ln -sf $f.gz.sh /bin/$f
done

if which uchaos >&3 && grep -q "UCTEST=1" /proc/cmdline; then
  dmesg -r | head -c 8192 > d.txt
  echo
  echo "DEVEL TEST START"
  echo
  echo "Preliminary speed and stats check"
  echo; uchaos -K512 < d.txt >/dev/null
  echo "Generating randomness by $(uchaos -v 2>&1)"
  n=0
  let n++; printf "Chunks: "
  for n in $(seq 8); do uchaos -qS -M1 < d.txt >$n.dat; printf "$n "; done
  printf "\n\n"
  cat *.dat | RNG_test stdin64 -tlshow 1024K
  printf "Files: "; ls -1 *.dat | tr '\t\n' '  '; echo
fi
