#!/bin/sh
# (c) 2026, Roberto A. Foglietta <roberto.foglietta@gmail.com>, MIT license

echo
mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs none /dev

bttm=$(cut -d' ' -f1 /proc/uptime)
( find / >/dev/null 2>&1 & )

mkdir -p /etc/init.d
touch /etc/init.d/rcS
chmod +x /etc/init.d/rcS

mkdir -p /var/log
touch /var/log/syslog

uname -a; sleep 1; echo "

      ===============================================
      Welcome to Minimal Linux System for QEMU x86_64
                System uptime $bttm seconds          
      ===============================================
"
exec /linuxrc
