#!/bin/sh
echo
mount -t proc none /proc
mount -t sysfs none /sys
mount -t devtmpfs none /dev

bttm=$(cut -d' ' -f1 /proc/uptime)
( find / >/dev/null 2>&1 & )

mkdir -p /etc/init.d
touch /etc/init.d/rcS
chmod +x /etc/init.d/rcS
uname -a

sleep 1; echo "

      ===============================================
      Welcome to Minimal Linux System for QEMU x86_64
                System uptime $bttm seconds          
      ===============================================
"
exec /linuxrc
